export const regionNames: Record<string, string> = {
  IDF: "Île-de-France",
  NOR: "Normandy",
  BRE: "Brittany",
  OCC: "Occitanie",
  ENG: "England",
  SCT: "Scotland",
  WLS: "Wales",
  NIR: "Northern Ireland",
  CAT: "Catalonia",
  AND: "Andijan",
  BAS: "Basque Country",
  TUS: "Tuscany",
  LOM: "Lombardy",
  BAV: "Bavaria",
  NRW: "North Rhine-Westphalia",
  UUS: "Uusimaa",
  VAS: "Western Finland",
  STH: "Stockholm",
  VGL: "Västra Götaland",
  SKA: "Skåne",
  OSLO: "Oslo",
  VIK: "Viken",
  VEST: "Vestland",
  AGS: "Attica",
  CEN: "Central Macedonia",
  IST: "Istanbul",
  ANK: "Ankara",
  IZM: "İzmir",
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arunachal Pradesh",
  CA: "California",
  CO: "Colorado",
  CT: "Chhattisgarh",
  DE: "Delaware",
  FL: "Florida",
  GA: "Goa",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Manipur",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "Inner Mongolia",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "Shandong",
  TN: "Tamil Nadu",
  TX: "Texas",
  UT: "Uttarakhand",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Western Australia",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  DC: "Washington, D.C.",
  AB: "Alberta",
  BC: "British Columbia",
  MB: "Manitoba",
  NB: "New Brunswick",
  NL: "Nagaland",
  NS: "Nova Scotia",
  NT: "Northern Territory",
  NU: "Nunavut",
  ON: "Ontario",
  PE: "Prince Edward Island",
  QC: "Quebec",
  SK: "Sikkim",
  YT: "Yukon",
  BCN: "Baja California",
  CHIH: "Chihuahua",
  JAL: "Jalal-Abad",
  MEX: "State of Mexico",
  VER: "Veracruz",
  YUC: "Yucatán",
  BA: "Barka",
  CBA: "Córdoba",
  SF: "Santa Fe",
  SP: "São Paulo",
  RJ: "Rajasthan",
  MG: "Minas Gerais",
  RS: "Rio Grande do Sul",
  AMA: "Amazonas",
  BOL: "Bolívar",
  ANT: "Antioquia",
  CUN: "Cundinamarca",
  LIM: "Lima",
  ARE: "Arequipa",
  CUS: "Cusco",
  SGO: "Santiago",
  VAL: "Valparaíso",
  BJ: "Beijing",
  SH: "Shanghai",
  GD: "Guangdong",
  JS: "Jiangsu",
  ZJ: "Zhejiang",
  SAx: "Sichuan",
  HEN: "Henan",
  HEB: "Hebei",
  HUN: "Hunan",
  AH: "Anhui",
  HUB: "Hubei",
  GX: "Guangxi",
  YN: "Yunnan",
  JX: "Jiangxi",
  LN: "Liaoning",
  FJ: "Fujian",
  SNx: "Shaanxi",
  HLJ: "Heilongjiang",
  SXx: "Shanxi",
  GZ: "Guizhou",
  JL: "Jilin",
  TJ: "Tianjin",
  GS: "Gansu",
  TW: "Taiwan",
  XJ: "Xinjiang",
  HK: "Hong Kong",
  MC: "Macau",
  JK: "Jammu and Kashmir",
  MH: "Maharashtra",
  UP: "Uttar Pradesh",
  WB: "West Bengal",
  BR: "Bihar",
  MP: "Madhya Pradesh",
  KA: "Karnataka",
  GJ: "Gujarat",
  AP: "Andhra Pradesh",
  OD: "Odisha",
  KL: "Kerala",
  TL: "Telangana",
  AS: "Assam",
  PB: "Punjab",
  HR: "Haryana",
  JH: "Jharkhand",
  HP: "Himachal Pradesh",
  TR: "Tripura",
  ML: "Meghalaya",
  MZ: "Mizoram",
  DL: "Delhi",
  PK: "Puducherry",
  AN: "Andaman and Nicobar Islands",
  CHD: "Chandigarh",
  DN: "Dadra and Nagar Haveli and Daman and Diu",
  LD: "Lakshadweep",
  KTK: "Kanto",
  KAN: "Kano",
  CHB: "Chūbu",
  KYU: "Kyushu",
  TOH: "Tōhoku",
  CHG: "Chūgoku",
  HOK: "Hokkaido",
  SHI: "Shikoku",
  SEL: "Seoul",
  BUS: "Busan",
  INC: "Incheon",
  GYE: "Gyeonggi",
  JOR: "Johor",
  SELx: "Selangor",
  PNH: "Phnom Penh",
  HAN: "Hanoi",
  HCM: "Ho Chi Minh City",
  JKT: "Jakarta",
  WJA: "West Java",
  EJA: "East Java",
  NSu: "North Sumatra",
  BKK: "Bangkok",
  NRT: "Nakhon Ratchasima",
  UDN: "Udon Thani",
  KHL: "Khon Kaen",
  LP: "Lampang",
  RGN: "Yangon",
  MDY: "Mandalay",
  DHK: "Dhaka",
  CTG: "Chittagong",
  KHI: "Karachi",
  LHR: "Lahore",
  ISL: "Islamabad",
  PES: "Peshawar",
  QTA: "Quetta",
  FAI: "Faisalabad",
  RWP: "Rawalpindi",
  MUL: "Multan",
  GJR: "Gujranwala",
  HYD: "Hyderabad",
  COL: "Colombo",
  KANy: "Kandy",
  GAL: "Galle",
  JAF: "Jaffna",
  DAM: "Damascus",
  ALE: "Alexandria",
  HOM: "Homs",
  LTK: "Latakia",
  AMM: "Amman",
  IRB: "Irbid",
  ZAR: "Zarqa",
  AHD: "Ahvaz",
  MSH: "Mashhad",
  TAB: "Tabriz",
  SHR: "Shiraz",
  CAI: "Cairo",
  GIZ: "Giza",
  SHA: "Sharqia",
  JO: "Johannesburg",
  CPT: "Cape Town",
  EKU: "Ekurhuleni",
  ETH: "eThekwini",
  TSH: "Tashkent",
  NEL: "Nelson Mandela Bay",
  BUF: "Buffalo City",
  LAG: "Lagos",
  IBD: "Ibadan",
  BEN: "Benguela",
  KAD: "Kaduna",
  ABJ: "Abuja",
  ACC: "Accra",
  KUM: "Kumasi",
  TAM: "Tambov",
  TAK: "Takoradi",
  NRB: "Nairobi",
  MSA: "Mombasa",
  KIS: "Kisumu",
  NAK: "Nakuru",
  ADD: "Addis Ababa",
  DIR: "Dire Dawa",
  MEK: "Mekelle",
  GON: "Gondar",
  HAR: "Harari",
  KIG: "Kigali",
  BUT: "Butare",
  GIT: "Gitarama",
  RUH: "Ruhengeri",
  DAR: "Dar es Salaam",
  MWA: "Mwanza",
  ARU: "Arusha",
  DSM: "Dodoma",
  KAM: "Kampala",
  MBL: "Mbale",
  MAS: "Masaka",
  GUL: "Gulu",
  KHA: "Khabarovsk",
  NYA: "Nyala",
  POR: "Port Sudan",
  KAS: "Kassala",
  ALG: "Algiers",
  ORA: "Oral",
  CON: "Constantine",
  ANN: "Annaba",
  TUN: "Tunis",
  SFx: "Sfax",
  SOS: "Sousse",
  KAI: "Kairouan",
  CAS: "Casablanca",
  RAB: "Rabat",
  FES: "Fès",
  TAN: "Tangier",
  MAP: "Maputo",
  BEI: "Beira",
  NAM: "Namangan",
  CHI: "Chita",
  LUA: "Luanda",
  HUA: "Huambo",
  LUB: "Lubango",
  KIN: "Kinshasa",
  KISx: "Kisangani",
  MAI: "Mbandaka",
  KANx: "Kananga",
  BRA: "Brazzaville",
  POI: "Pointe-Noire",
  DOL: "Dolisie",
  OWE: "Owando",
  LIB: "Monrovia",
  GB: "Gbarnga",
  KAK: "Kakata",
  HARx: "Harper",
  FRE: "Freetown",
  KEN: "Kenema",
  BO: "Bo",
  MAK: "Makeni",
  BAN: "Banjul",
  KOM: "Kombo",
  KANz: "Kanifing",
  BRI: "Brikama",
  BAM: "Bamako",
  SIK: "Sikasso",
  KAY: "Kayes",
  KOU: "Koutiala",
  OUA: "Ouagadougou",
  BOB: "Bobo-Dioulasso",
  KOUx: "Koudougou",
  OUAH: "Ouahigouya",
  NIA: "Niamey",
  ZIN: "Zinder",
  MAR: "Maradi",
  TAH: "Tahoua",
  NDJ: "N'Djamena",
  MOU: "Moundou",
  SAR: "Saratov",
  ABE: "Abéché",
  OUAy: "Ouagadougou",
  BOBy: "Bobo-Dioulasso",
  NSW: "New South Wales",
  VIC: "Victoria",
  QLD: "Queensland",
  SA: "South Australia",
  TAS: "Tasmania",
  ACT: "Australian Capital Territory",
  AUK: "Auckland",
  CAN: "Canterbury",
  WEL: "Wellington",
  OTA: "Otago",
  WAI: "Waikato",
  BOP: "Bay of Plenty",
  MAN: "Manawatū-Whanganui",
  HKB: "Hawke's Bay",
  TAR: "Taraz",
  GIS: "Gisborne",
  NELx: "Nelson",
  MARx: "Mary",
  TASx: "Tasman",
  WTC: "West Coast",
  STC: "Southland",
  NCD: "National Capital District (Port Moresby)",
  MOR: "Morobe",
  EHP: "Eastern Highlands",
  WHP: "Western Highlands",
  ESP: "East Sepik",
  WES: "West Sepik",
  DXB: "Dubai",
  AUH: "Abu Dhabi",
  SHJ: "Sharjah",
  DOH: "Doha",
  RAY: "Al Rayyan",
  WAK: "Al Wakrah",
  KWT: "Kuwait City",
  AHM: "Ahmadi",
  JLE: "Jahra",
  FAR: "Farwaniya",
  MCT: "Muscat",
  SU: "Sur",
  SLH: "Salalah",
  SOH: "Sohar",
  BAH: "Manama",
  MUH: "Muharraq",
  RIF: "Riffa",
  HAM: "Hamad Town",
  AMMx: "Amman",
  ZARx: "Zarqa",
  IRBx: "Irbid",
  RUS: "Russeifa",
  AQ: "Aqaba",
  MOW: "Moscow",
  SPE: "Saint Petersburg",
  NVS: "Novosibirsk",
  EKT: "Yekaterinburg",
  KZN: "Kazan",
  NIZ: "Nizhny Novgorod",
  CHE: "Chelyabinsk",
  OMS: "Omsk",
  SAM: "Samara",
  ROS: "Rostov-on-Don",
  UFA: "Ufa",
  KRA: "Krasnoyarsk",
  VOR: "Voronezh",
  PER: "Perm",
  VOL: "Volgograd",
  KRAx: "Krasnodar",
  TYU: "Tyumen",
  TOL: "Tolyatti",
  IZV: "Izhevsk",
  ULY: "Ulyanovsk",
  BRY: "Bryansk",
  KUR: "Kursk",
  TUL: "Tula",
  LIP: "Lipetsk",
  ORE: "Orenburg",
  PEN: "Penza",
  SARx: "Saransk",
  YAR: "Yaroslavl",
  RYA: "Ryazan",
  BEL: "Belgorod",
  VLA: "Vladimir",
  KURx: "Kurgan",
  KIR: "Kiribati",
  NGR: "Nizhny Tagil",
  MAG: "Magnitogorsk",
  TYUx: "Tyumen",
  VLAy: "Vladivostok",
  IRT: "Irkutsk",
  KEM: "Kemerovo",
  NOV: "Novokuznetsk",
  OMSx: "Omsk",
  TOM: "Tomsk",
  BAR: "Barnaul",
  ULAN: "Ulan-Ude",
  YAK: "Yakutsk",
  BLA: "Blagoveshchensk",
  PET: "Petropavlovsk-Kamchatsky",
  YUZ: "Yuzhno-Sakhalinsk",
  ANA: "Anadyr",
  ALM: "Almaty",
  NUR: "Nur-Sultan",
  SHY: "Shymkent",
  KAR: "Karaganda",
  AKM: "Aktobe",
  PAV: "Pavlodar",
  UST: "Ust-Kamenogorsk",
  SEM: "Semey",
  SAMx: "Samarkand",
  BUK: "Bukhara",
  NUK: "Nukus",
  FARx: "Fergana",
  KOK: "Kokand",
  DUS: "Dushanbe",
  KHU: "Khujand",
  KUL: "Kulyab",
  KHO: "Khorog",
  BIS: "Bishkek",
  OSH: "Osh",
  KARx: "Karakol",
  TAL: "Nukus",
  ASH: "Ashgabat",
  TUR: "Türkmenabat",
  DAS: "Daşoguz",
  BAK: "Baku",
  GAN: "Ganja",
  SUM: "Sumqayit",
  MIN: "Mingachevir",
  TBI: "Tbilisi",
  KUT: "Kutaisi",
  BAT: "Batumi",
  RUSx: "Rustavi",
  YER: "Yerevan",
  GYU: "Gyumri",
  VAN: "Vanadzor",
  REU: "Réunion",
  MAY: "Mayotte",
  GUA: "Guadeloupe",
  MARy: "Martinique",
  GUF: "French Guiana",
  NCL: "New Caledonia",
  PYF: "French Polynesia",
  SPM: "Saint Pierre and Miquelon",
  WAL: "Wallis and Futuna",
  AIA: "Anguilla",
  ATG: "Antigua and Barbuda",
  BHS: "Bahamas",
  BRB: "Barbados",
  BLZ: "Belize",
  BMU: "Bermuda",
  VGB: "British Virgin Islands",
  CYM: "Cayman Islands",
  CRI: "Costa Rica",
  CUB: "Cuba",
  DMA: "Dominica",
  DOM: "Dominican Republic",
  SLV: "El Salvador",
  GRD: "Grenada",
  GTM: "Guatemala",
  HTI: "Haiti",
  HND: "Honduras",
  JAM: "Jamaica",
  NIC: "Nicaragua",
  PAN: "Panama",
  KNA: "Saint Kitts and Nevis",
  LCA: "Saint Lucia",
  VCT: "Saint Vincent and the Grenadines",
  TTO: "Trinidad and Tobago",
  TCA: "Turks and Caicos Islands",
  VIR: "United States Virgin Islands",
  ASM: "American Samoa",
  COK: "Cook Islands",
  FJI: "Fiji",
  GUM: "Guam",
  MHL: "Marshall Islands",
  FSM: "Micronesia",
  NRU: "Nauru",
  NIU: "Niue",
  NFK: "Norfolk Island",
  MNP: "Northern Mariana Islands",
  PLW: "Palau",
  PNG: "Papua New Guinea",
  WSM: "Samoa",
  SLP: "Solomon Islands",
  TKL: "Tokelau",
  TON: "Tonga",
  TUV: "Tuvalu",
  VUT: "Vanuatu",
  WLF: "Wallis and Futuna",
};
