export const regionNames: Record<
  string,
  {
    regionId: string;
    regionName: string;
    countryFlag: string;
    countryName: string;
  }
> = {
  IDF: {
    regionId: "IDF",
    regionName: "Île-de-France",
    countryFlag: "🇫🇷",
    countryName: "France",
  },
  NOR: {
    regionId: "NOR",
    regionName: "Normandy",
    countryFlag: "🇫🇷",
    countryName: "France",
  },
  BRE: {
    regionId: "BRE",
    regionName: "Brittany",
    countryFlag: "🇫🇷",
    countryName: "France",
  },
  OCC: {
    regionId: "OCC",
    regionName: "Occitanie",
    countryFlag: "🇫🇷",
    countryName: "France",
  },
  ENG: {
    regionId: "ENG",
    regionName: "England",
    countryFlag: "🇬🇧",
    countryName: "United Kingdom",
  },
  SCT: {
    regionId: "SCT",
    regionName: "Scotland",
    countryFlag: "🇬🇧",
    countryName: "United Kingdom",
  },
  WLS: {
    regionId: "WLS",
    regionName: "Wales",
    countryFlag: "🇬🇧",
    countryName: "United Kingdom",
  },
  NIR: {
    regionId: "NIR",
    regionName: "Northern Ireland",
    countryFlag: "🇬🇧",
    countryName: "United Kingdom",
  },
  CAT: {
    regionId: "CAT",
    regionName: "Catalonia",
    countryFlag: "🇪🇸",
    countryName: "Spain",
  },
  AND: {
    regionId: "AND",
    regionName: "Andijan",
    countryFlag: "🇺🇿",
    countryName: "Uzbekistan",
  },
  BAS: {
    regionId: "BAS",
    regionName: "Basque Country",
    countryFlag: "🇪🇸",
    countryName: "Spain",
  },
  TUS: {
    regionId: "TUS",
    regionName: "Tuscany",
    countryFlag: "🇮🇹",
    countryName: "Italy",
  },
  LOM: {
    regionId: "LOM",
    regionName: "Lombardy",
    countryFlag: "🇮🇹",
    countryName: "Italy",
  },
  BAV: {
    regionId: "BAV",
    regionName: "Bavaria",
    countryFlag: "🇩🇪",
    countryName: "Germany",
  },
  NRW: {
    regionId: "NRW",
    regionName: "North Rhine-Westphalia",
    countryFlag: "🇩🇪",
    countryName: "Germany",
  },
  UUS: {
    regionId: "UUS",
    regionName: "Uusimaa",
    countryFlag: "🇫🇮",
    countryName: "Finland",
  },
  VAS: {
    regionId: "VAS",
    regionName: "Western Finland",
    countryFlag: "🇫🇮",
    countryName: "Finland",
  },
  STH: {
    regionId: "STH",
    regionName: "Stockholm",
    countryFlag: "🇸🇪",
    countryName: "Sweden",
  },
  VGL: {
    regionId: "VGL",
    regionName: "Västra Götaland",
    countryFlag: "🇸🇪",
    countryName: "Sweden",
  },
  SKA: {
    regionId: "SKA",
    regionName: "Skåne",
    countryFlag: "🇸🇪",
    countryName: "Sweden",
  },
  OSLO: {
    regionId: "OSLO",
    regionName: "Oslo",
    countryFlag: "🇳🇴",
    countryName: "Norway",
  },
  VIK: {
    regionId: "VIK",
    regionName: "Viken",
    countryFlag: "🇳🇴",
    countryName: "Norway",
  },
  VEST: {
    regionId: "VEST",
    regionName: "Vestland",
    countryFlag: "🇳🇴",
    countryName: "Norway",
  },
  AGS: {
    regionId: "AGS",
    regionName: "Attica",
    countryFlag: "🇬🇷",
    countryName: "Greece",
  },
  CEN: {
    regionId: "CEN",
    regionName: "Central Macedonia",
    countryFlag: "🇬🇷",
    countryName: "Greece",
  },
  IST: {
    regionId: "IST",
    regionName: "Istanbul",
    countryFlag: "🇹🇷",
    countryName: "Turkey",
  },
  ANK: {
    regionId: "ANK",
    regionName: "Ankara",
    countryFlag: "🇹🇷",
    countryName: "Turkey",
  },
  IZM: {
    regionId: "IZM",
    regionName: "İzmir",
    countryFlag: "🇹🇷",
    countryName: "Turkey",
  },
  AL: {
    regionId: "AL",
    regionName: "Alabama",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  AK: {
    regionId: "AK",
    regionName: "Alaska",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  AZ: {
    regionId: "AZ",
    regionName: "Arizona",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  AR: {
    regionId: "AR",
    regionName: "Arunachal Pradesh",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  CA: {
    regionId: "CA",
    regionName: "California",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  CO: {
    regionId: "CO",
    regionName: "Colorado",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  CT: {
    regionId: "CT",
    regionName: "Chhattisgarh",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  DE: {
    regionId: "DE",
    regionName: "Delaware",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  FL: {
    regionId: "FL",
    regionName: "Florida",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  GA: {
    regionId: "GA",
    regionName: "Goa",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  HI: {
    regionId: "HI",
    regionName: "Hawaii",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  ID: {
    regionId: "ID",
    regionName: "Idaho",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  IL: {
    regionId: "IL",
    regionName: "Illinois",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  IN: {
    regionId: "IN",
    regionName: "Indiana",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  IA: {
    regionId: "IA",
    regionName: "Iowa",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  KS: {
    regionId: "KS",
    regionName: "Kansas",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  KY: {
    regionId: "KY",
    regionName: "Kentucky",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  LA: {
    regionId: "LA",
    regionName: "Louisiana",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  ME: {
    regionId: "ME",
    regionName: "Maine",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  MD: {
    regionId: "MD",
    regionName: "Maryland",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  MA: {
    regionId: "MA",
    regionName: "Massachusetts",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  MI: {
    regionId: "MI",
    regionName: "Michigan",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  MN: {
    regionId: "MN",
    regionName: "Manipur",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  MS: {
    regionId: "MS",
    regionName: "Mississippi",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  MO: {
    regionId: "MO",
    regionName: "Missouri",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  MT: {
    regionId: "MT",
    regionName: "Montana",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  NE: {
    regionId: "NE",
    regionName: "Nebraska",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  NV: {
    regionId: "NV",
    regionName: "Nevada",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  NH: {
    regionId: "NH",
    regionName: "New Hampshire",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  NJ: {
    regionId: "NJ",
    regionName: "New Jersey",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  NM: {
    regionId: "NM",
    regionName: "Inner Mongolia",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  NY: {
    regionId: "NY",
    regionName: "New York",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  NC: {
    regionId: "NC",
    regionName: "North Carolina",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  ND: {
    regionId: "ND",
    regionName: "North Dakota",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  OH: {
    regionId: "OH",
    regionName: "Ohio",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  OK: {
    regionId: "OK",
    regionName: "Oklahoma",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  OR: {
    regionId: "OR",
    regionName: "Oregon",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  PA: {
    regionId: "PA",
    regionName: "Pennsylvania",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  RI: {
    regionId: "RI",
    regionName: "Rhode Island",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  SC: {
    regionId: "SC",
    regionName: "South Carolina",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  SD: {
    regionId: "SD",
    regionName: "Shandong",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  TN: {
    regionId: "TN",
    regionName: "Tamil Nadu",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  TX: {
    regionId: "TX",
    regionName: "Texas",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  UT: {
    regionId: "UT",
    regionName: "Uttarakhand",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  VT: {
    regionId: "VT",
    regionName: "Vermont",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  VA: {
    regionId: "VA",
    regionName: "Virginia",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  WA: {
    regionId: "WA",
    regionName: "Western Australia",
    countryFlag: "🇦🇺",
    countryName: "Australia",
  },
  WV: {
    regionId: "WV",
    regionName: "West Virginia",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  WI: {
    regionId: "WI",
    regionName: "Wisconsin",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  WY: {
    regionId: "WY",
    regionName: "Wyoming",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  DC: {
    regionId: "DC",
    regionName: "Washington, D.C.",
    countryFlag: "🇺🇸",
    countryName: "United States",
  },
  AB: {
    regionId: "AB",
    regionName: "Alberta",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  BC: {
    regionId: "BC",
    regionName: "British Columbia",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  MB: {
    regionId: "MB",
    regionName: "Manitoba",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  NB: {
    regionId: "NB",
    regionName: "New Brunswick",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  NL: {
    regionId: "NL",
    regionName: "Nagaland",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  NS: {
    regionId: "NS",
    regionName: "Nova Scotia",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  NT: {
    regionId: "NT",
    regionName: "Northern Territory",
    countryFlag: "🇦🇺",
    countryName: "Australia",
  },
  NU: {
    regionId: "NU",
    regionName: "Nunavut",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  ON: {
    regionId: "ON",
    regionName: "Ontario",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  PE: {
    regionId: "PE",
    regionName: "Prince Edward Island",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  QC: {
    regionId: "QC",
    regionName: "Quebec",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  SK: {
    regionId: "SK",
    regionName: "Sikkim",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  YT: {
    regionId: "YT",
    regionName: "Yukon",
    countryFlag: "🇨🇦",
    countryName: "Canada",
  },
  BCN: {
    regionId: "BCN",
    regionName: "Baja California",
    countryFlag: "🇲🇽",
    countryName: "Mexico",
  },
  CHIH: {
    regionId: "CHIH",
    regionName: "Chihuahua",
    countryFlag: "🇲🇽",
    countryName: "Mexico",
  },
  JAL: {
    regionId: "JAL",
    regionName: "Jalal-Abad",
    countryFlag: "🇰🇬",
    countryName: "Kyrgyzstan",
  },
  MEX: {
    regionId: "MEX",
    regionName: "State of Mexico",
    countryFlag: "🇲🇽",
    countryName: "Mexico",
  },
  VER: {
    regionId: "VER",
    regionName: "Veracruz",
    countryFlag: "🇲🇽",
    countryName: "Mexico",
  },
  YUC: {
    regionId: "YUC",
    regionName: "Yucatán",
    countryFlag: "🇲🇽",
    countryName: "Mexico",
  },
  BA: {
    regionId: "BA",
    regionName: "Barka",
    countryFlag: "🇪🇷",
    countryName: "Eritrea",
  },
  CBA: {
    regionId: "CBA",
    regionName: "Córdoba",
    countryFlag: "🇦🇷",
    countryName: "Argentina",
  },
  SF: {
    regionId: "SF",
    regionName: "Santa Fe",
    countryFlag: "🇦🇷",
    countryName: "Argentina",
  },
  SP: {
    regionId: "SP",
    regionName: "São Paulo",
    countryFlag: "🇧🇷",
    countryName: "Brazil",
  },
  RJ: {
    regionId: "RJ",
    regionName: "Rajasthan",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  MG: {
    regionId: "MG",
    regionName: "Minas Gerais",
    countryFlag: "🇧🇷",
    countryName: "Brazil",
  },
  RS: {
    regionId: "RS",
    regionName: "Rio Grande do Sul",
    countryFlag: "🇧🇷",
    countryName: "Brazil",
  },
  AMA: {
    regionId: "AMA",
    regionName: "Amazonas",
    countryFlag: "🇧🇷",
    countryName: "Brazil",
  },
  BOL: {
    regionId: "BOL",
    regionName: "Bolívar",
    countryFlag: "🇻🇪",
    countryName: "Venezuela",
  },
  ANT: {
    regionId: "ANT",
    regionName: "Antioquia",
    countryFlag: "🇨🇴",
    countryName: "Colombia",
  },
  CUN: {
    regionId: "CUN",
    regionName: "Cundinamarca",
    countryFlag: "🇨🇴",
    countryName: "Colombia",
  },
  LIM: {
    regionId: "LIM",
    regionName: "Lima",
    countryFlag: "🇵🇪",
    countryName: "Peru",
  },
  ARE: {
    regionId: "ARE",
    regionName: "Arequipa",
    countryFlag: "🇵🇪",
    countryName: "Peru",
  },
  CUS: {
    regionId: "CUS",
    regionName: "Cusco",
    countryFlag: "🇵🇪",
    countryName: "Peru",
  },
  SGO: {
    regionId: "SGO",
    regionName: "Santiago",
    countryFlag: "🇨🇱",
    countryName: "Chile",
  },
  VAL: {
    regionId: "VAL",
    regionName: "Valparaíso",
    countryFlag: "🇨🇱",
    countryName: "Chile",
  },
  BJ: {
    regionId: "BJ",
    regionName: "Beijing",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  SH: {
    regionId: "SH",
    regionName: "Shanghai",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  GD: {
    regionId: "GD",
    regionName: "Guangdong",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  JS: {
    regionId: "JS",
    regionName: "Jiangsu",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  ZJ: {
    regionId: "ZJ",
    regionName: "Zhejiang",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  SAx: {
    regionId: "SAx",
    regionName: "Sichuan",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  HEN: {
    regionId: "HEN",
    regionName: "Henan",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  HEB: {
    regionId: "HEB",
    regionName: "Hebei",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  HUN: {
    regionId: "HUN",
    regionName: "Hunan",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  AH: {
    regionId: "AH",
    regionName: "Anhui",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  HUB: {
    regionId: "HUB",
    regionName: "Hubei",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  GX: {
    regionId: "GX",
    regionName: "Guangxi",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  YN: {
    regionId: "YN",
    regionName: "Yunnan",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  JX: {
    regionId: "JX",
    regionName: "Jiangxi",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  LN: {
    regionId: "LN",
    regionName: "Liaoning",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  FJ: {
    regionId: "FJ",
    regionName: "Fujian",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  SNx: {
    regionId: "SNx",
    regionName: "Shaanxi",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  HLJ: {
    regionId: "HLJ",
    regionName: "Heilongjiang",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  SXx: {
    regionId: "SXx",
    regionName: "Shanxi",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  GZ: {
    regionId: "GZ",
    regionName: "Guizhou",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  JL: {
    regionId: "JL",
    regionName: "Jilin",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  TJ: {
    regionId: "TJ",
    regionName: "Tianjin",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  GS: {
    regionId: "GS",
    regionName: "Gansu",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  TW: {
    regionId: "TW",
    regionName: "Taiwan",
    countryFlag: "🇹🇼",
    countryName: "Taiwan",
  },
  XJ: {
    regionId: "XJ",
    regionName: "Xinjiang",
    countryFlag: "🇨🇳",
    countryName: "China",
  },
  HK: {
    regionId: "HK",
    regionName: "Hong Kong",
    countryFlag: "🇭🇰",
    countryName: "Hong Kong",
  },
  MC: {
    regionId: "MC",
    regionName: "Macau",
    countryFlag: "🇲🇴",
    countryName: "Macau",
  },
  JK: {
    regionId: "JK",
    regionName: "Jammu and Kashmir",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  MH: {
    regionId: "MH",
    regionName: "Maharashtra",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  UP: {
    regionId: "UP",
    regionName: "Uttar Pradesh",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  WB: {
    regionId: "WB",
    regionName: "West Bengal",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  BR: {
    regionId: "BR",
    regionName: "Bihar",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  MP: {
    regionId: "MP",
    regionName: "Madhya Pradesh",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  KA: {
    regionId: "KA",
    regionName: "Karnataka",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  GJ: {
    regionId: "GJ",
    regionName: "Gujarat",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  AP: {
    regionId: "AP",
    regionName: "Andhra Pradesh",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  OD: {
    regionId: "OD",
    regionName: "Odisha",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  KL: {
    regionId: "KL",
    regionName: "Kerala",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  TL: {
    regionId: "TL",
    regionName: "Telangana",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  AS: {
    regionId: "AS",
    regionName: "Assam",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  PB: {
    regionId: "PB",
    regionName: "Punjab",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  HR: {
    regionId: "HR",
    regionName: "Haryana",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  JH: {
    regionId: "JH",
    regionName: "Jharkhand",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  HP: {
    regionId: "HP",
    regionName: "Himachal Pradesh",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  TR: {
    regionId: "TR",
    regionName: "Tripura",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  ML: {
    regionId: "ML",
    regionName: "Meghalaya",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  MZ: {
    regionId: "MZ",
    regionName: "Mizoram",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  DL: {
    regionId: "DL",
    regionName: "Delhi",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  PK: {
    regionId: "PK",
    regionName: "Puducherry",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  AN: {
    regionId: "AN",
    regionName: "Andaman and Nicobar Islands",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  CHD: {
    regionId: "CHD",
    regionName: "Chandigarh",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  DN: {
    regionId: "DN",
    regionName: "Dadra and Nagar Haveli and Daman and Diu",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  LD: {
    regionId: "LD",
    regionName: "Lakshadweep",
    countryFlag: "🇮🇳",
    countryName: "India",
  },
  KTK: {
    regionId: "KTK",
    regionName: "Kanto",
    countryFlag: "🇯🇵",
    countryName: "Japan",
  },
  KAN: {
    regionId: "KAN",
    regionName: "Kano",
    countryFlag: "🇳🇬",
    countryName: "Nigeria",
  },
  CHB: {
    regionId: "CHB",
    regionName: "Chūbu",
    countryFlag: "🇯🇵",
    countryName: "Japan",
  },
  KYU: {
    regionId: "KYU",
    regionName: "Kyushu",
    countryFlag: "🇯🇵",
    countryName: "Japan",
  },
  TOH: {
    regionId: "TOH",
    regionName: "Tōhoku",
    countryFlag: "🇯🇵",
    countryName: "Japan",
  },
  CHG: {
    regionId: "CHG",
    regionName: "Chūgoku",
    countryFlag: "🇯🇵",
    countryName: "Japan",
  },
  HOK: {
    regionId: "HOK",
    regionName: "Hokkaido",
    countryFlag: "🇯🇵",
    countryName: "Japan",
  },
  SHI: {
    regionId: "SHI",
    regionName: "Shikoku",
    countryFlag: "🇯🇵",
    countryName: "Japan",
  },
  SEL: {
    regionId: "SEL",
    regionName: "Seoul",
    countryFlag: "🇰🇷",
    countryName: "South Korea",
  },
  BUS: {
    regionId: "BUS",
    regionName: "Busan",
    countryFlag: "🇰🇷",
    countryName: "South Korea",
  },
  INC: {
    regionId: "INC",
    regionName: "Incheon",
    countryFlag: "🇰🇷",
    countryName: "South Korea",
  },
  GYE: {
    regionId: "GYE",
    regionName: "Gyeonggi",
    countryFlag: "🇰🇷",
    countryName: "South Korea",
  },
  JOR: {
    regionId: "JOR",
    regionName: "Johor",
    countryFlag: "🇲🇾",
    countryName: "Malaysia",
  },
  SELx: {
    regionId: "SELx",
    regionName: "Selangor",
    countryFlag: "🇲🇾",
    countryName: "Malaysia",
  },
  PNH: {
    regionId: "PNH",
    regionName: "Phnom Penh",
    countryFlag: "🇰🇭",
    countryName: "Cambodia",
  },
  HAN: {
    regionId: "HAN",
    regionName: "Hanoi",
    countryFlag: "🇻🇳",
    countryName: "Vietnam",
  },
  HCM: {
    regionId: "HCM",
    regionName: "Ho Chi Minh City",
    countryFlag: "🇻🇳",
    countryName: "Vietnam",
  },
  JKT: {
    regionId: "JKT",
    regionName: "Jakarta",
    countryFlag: "🇮🇩",
    countryName: "Indonesia",
  },
  WJA: {
    regionId: "WJA",
    regionName: "West Java",
    countryFlag: "🇮🇩",
    countryName: "Indonesia",
  },
  EJA: {
    regionId: "EJA",
    regionName: "East Java",
    countryFlag: "🇮🇩",
    countryName: "Indonesia",
  },
  NSu: {
    regionId: "NSu",
    regionName: "North Sumatra",
    countryFlag: "🇮🇩",
    countryName: "Indonesia",
  },
  BKK: {
    regionId: "BKK",
    regionName: "Bangkok",
    countryFlag: "🇹🇭",
    countryName: "Thailand",
  },
  NRT: {
    regionId: "NRT",
    regionName: "Nakhon Ratchasima",
    countryFlag: "🇹🇭",
    countryName: "Thailand",
  },
  UDN: {
    regionId: "UDN",
    regionName: "Udon Thani",
    countryFlag: "🇹🇭",
    countryName: "Thailand",
  },
  KHL: {
    regionId: "KHL",
    regionName: "Khon Kaen",
    countryFlag: "🇹🇭",
    countryName: "Thailand",
  },
  LP: {
    regionId: "LP",
    regionName: "Lampang",
    countryFlag: "🇹🇭",
    countryName: "Thailand",
  },
  RGN: {
    regionId: "RGN",
    regionName: "Yangon",
    countryFlag: "🇲🇲",
    countryName: "Myanmar",
  },
  MDY: {
    regionId: "MDY",
    regionName: "Mandalay",
    countryFlag: "🇲🇲",
    countryName: "Myanmar",
  },
  DHK: {
    regionId: "DHK",
    regionName: "Dhaka",
    countryFlag: "🇧🇩",
    countryName: "Bangladesh",
  },
  CTG: {
    regionId: "CTG",
    regionName: "Chittagong",
    countryFlag: "🇧🇩",
    countryName: "Bangladesh",
  },
  KHI: {
    regionId: "KHI",
    regionName: "Karachi",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  LHR: {
    regionId: "LHR",
    regionName: "Lahore",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  ISL: {
    regionId: "ISL",
    regionName: "Islamabad",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  PES: {
    regionId: "PES",
    regionName: "Peshawar",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  QTA: {
    regionId: "QTA",
    regionName: "Quetta",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  FAI: {
    regionId: "FAI",
    regionName: "Faisalabad",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  RWP: {
    regionId: "RWP",
    regionName: "Rawalpindi",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  MUL: {
    regionId: "MUL",
    regionName: "Multan",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  GJR: {
    regionId: "GJR",
    regionName: "Gujranwala",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  HYD: {
    regionId: "HYD",
    regionName: "Hyderabad",
    countryFlag: "🇵🇰",
    countryName: "Pakistan",
  },
  COL: {
    regionId: "COL",
    regionName: "Colombo",
    countryFlag: "🇱🇰",
    countryName: "Sri Lanka",
  },
  KANy: {
    regionId: "KANy",
    regionName: "Kandy",
    countryFlag: "🇱🇰",
    countryName: "Sri Lanka",
  },
  GAL: {
    regionId: "GAL",
    regionName: "Galle",
    countryFlag: "🇱🇰",
    countryName: "Sri Lanka",
  },
  JAF: {
    regionId: "JAF",
    regionName: "Jaffna",
    countryFlag: "🇱🇰",
    countryName: "Sri Lanka",
  },
  DAM: {
    regionId: "DAM",
    regionName: "Damascus",
    countryFlag: "🇸🇾",
    countryName: "Syria",
  },
  ALE: {
    regionId: "ALE",
    regionName: "Alexandria",
    countryFlag: "🇪🇬",
    countryName: "Egypt",
  },
  HOM: {
    regionId: "HOM",
    regionName: "Homs",
    countryFlag: "🇸🇾",
    countryName: "Syria",
  },
  LTK: {
    regionId: "LTK",
    regionName: "Latakia",
    countryFlag: "🇸🇾",
    countryName: "Syria",
  },
  AMM: {
    regionId: "AMM",
    regionName: "Amman",
    countryFlag: "🇯🇴",
    countryName: "Jordan",
  },
  IRB: {
    regionId: "IRB",
    regionName: "Irbid",
    countryFlag: "🇯🇴",
    countryName: "Jordan",
  },
  ZAR: {
    regionId: "ZAR",
    regionName: "Zarqa",
    countryFlag: "🇯🇴",
    countryName: "Jordan",
  },
  AHD: {
    regionId: "AHD",
    regionName: "Ahvaz",
    countryFlag: "🇮🇷",
    countryName: "Iran",
  },
  MSH: {
    regionId: "MSH",
    regionName: "Mashhad",
    countryFlag: "🇮🇷",
    countryName: "Iran",
  },
  TAB: {
    regionId: "TAB",
    regionName: "Tabriz",
    countryFlag: "🇮🇷",
    countryName: "Iran",
  },
  SHR: {
    regionId: "SHR",
    regionName: "Shiraz",
    countryFlag: "🇮🇷",
    countryName: "Iran",
  },
  CAI: {
    regionId: "CAI",
    regionName: "Cairo",
    countryFlag: "🇪🇬",
    countryName: "Egypt",
  },
  GIZ: {
    regionId: "GIZ",
    regionName: "Giza",
    countryFlag: "🇪🇬",
    countryName: "Egypt",
  },
  SHA: {
    regionId: "SHA",
    regionName: "Sharqia",
    countryFlag: "🇪🇬",
    countryName: "Egypt",
  },
  JO: {
    regionId: "JO",
    regionName: "Johannesburg",
    countryFlag: "🇿🇦",
    countryName: "South Africa",
  },
  CPT: {
    regionId: "CPT",
    regionName: "Cape Town",
    countryFlag: "🇿🇦",
    countryName: "South Africa",
  },
  EKU: {
    regionId: "EKU",
    regionName: "Ekurhuleni",
    countryFlag: "🇿🇦",
    countryName: "South Africa",
  },
  ETH: {
    regionId: "ETH",
    regionName: "eThekwini",
    countryFlag: "🇿🇦",
    countryName: "South Africa",
  },
  TSH: {
    regionId: "TSH",
    regionName: "Tashkent",
    countryFlag: "🇺🇿",
    countryName: "Uzbekistan",
  },
  NEL: {
    regionId: "NEL",
    regionName: "Nelson Mandela Bay",
    countryFlag: "🇿🇦",
    countryName: "South Africa",
  },
  BUF: {
    regionId: "BUF",
    regionName: "Buffalo City",
    countryFlag: "🇿🇦",
    countryName: "South Africa",
  },
  LAG: {
    regionId: "LAG",
    regionName: "Lagos",
    countryFlag: "🇳🇬",
    countryName: "Nigeria",
  },
  IBD: {
    regionId: "IBD",
    regionName: "Ibadan",
    countryFlag: "🇳🇬",
    countryName: "Nigeria",
  },
  BEN: {
    regionId: "BEN",
    regionName: "Benguela",
    countryFlag: "🇦🇴",
    countryName: "Angola",
  },
  KAD: {
    regionId: "KAD",
    regionName: "Kaduna",
    countryFlag: "🇳🇬",
    countryName: "Nigeria",
  },
  ABJ: {
    regionId: "ABJ",
    regionName: "Abuja",
    countryFlag: "🇳🇬",
    countryName: "Nigeria",
  },
  ACC: {
    regionId: "ACC",
    regionName: "Accra",
    countryFlag: "🇬🇭",
    countryName: "Ghana",
  },
  KUM: {
    regionId: "KUM",
    regionName: "Kumasi",
    countryFlag: "🇬🇭",
    countryName: "Ghana",
  },
  TAM: {
    regionId: "TAM",
    regionName: "Tambov",
    countryFlag: "🇷🇺",
    countryName: "Russia",
  },
  TAK: {
    regionId: "TAK",
    regionName: "Takoradi",
    countryFlag: "🇬🇭",
    countryName: "Ghana",
  },
  NRB: {
    regionId: "NRB",
    regionName: "Nairobi",
    countryFlag: "🇰🇪",
    countryName: "Kenya",
  },
  MSA: {
    regionId: "MSA",
    regionName: "Mombasa",
    countryFlag: "🇰🇪",
    countryName: "Kenya",
  },
  KIS: {
    regionId: "KIS",
    regionName: "Kisumu",
    countryFlag: "🇰🇪",
    countryName: "Kenya",
  },
  NAK: {
    regionId: "NAK",
    regionName: "Nakuru",
    countryFlag: "🇰🇪",
    countryName: "Kenya",
  },
  ADD: {
    regionId: "ADD",
    regionName: "Addis Ababa",
    countryFlag: "🇪🇹",
    countryName: "Ethiopia",
  },
  DIR: {
    regionId: "DIR",
    regionName: "Dire Dawa",
    countryFlag: "🇪🇹",
    countryName: "Ethiopia",
  },
  MEK: {
    regionId: "MEK",
    regionName: "Mekelle",
    countryFlag: "🇪🇹",
    countryName: "Ethiopia",
  },
  GON: {
    regionId: "GON",
    regionName: "Gondar",
    countryFlag: "🇪🇹",
    countryName: "Ethiopia",
  },
  HAR: {
    regionId: "HAR",
    regionName: "Harari",
    countryFlag: "🇪🇹",
    countryName: "Ethiopia",
  },
  KIG: {
    regionId: "KIG",
    regionName: "Kigali",
    countryFlag: "🇷🇼",
    countryName: "Rwanda",
  },
  BUT: {
    regionId: "BUT",
    regionName: "Butare",
    countryFlag: "🇷🇼",
    countryName: "Rwanda",
  },
  GIT: {
    regionId: "GIT",
    regionName: "Gitarama",
    countryFlag: "🇷🇼",
    countryName: "Rwanda",
  },
  RUH: {
    regionId: "RUH",
    regionName: "Ruhengeri",
    countryFlag: "🇷🇼",
    countryName: "Rwanda",
  },
  DAR: {
    regionId: "DAR",
    regionName: "Dar es Salaam",
    countryFlag: "🇹🇿",
    countryName: "Tanzania",
  },
  MWA: {
    regionId: "MWA",
    regionName: "Mwanza",
    countryFlag: "🇹🇿",
    countryName: "Tanzania",
  },
  ARU: {
    regionId: "ARU",
    regionName: "Arusha",
    countryFlag: "🇹🇿",
    countryName: "Tanzania",
  },
  DSM: {
    regionId: "DSM",
    regionName: "Dodoma",
    countryFlag: "🇹🇿",
    countryName: "Tanzania",
  },
  KAM: {
    regionId: "KAM",
    regionName: "Kampala",
    countryFlag: "🇺🇬",
    countryName: "Uganda",
  },
  MBL: {
    regionId: "MBL",
    regionName: "Mbale",
    countryFlag: "🇺🇬",
    countryName: "Uganda",
  },
  MAS: {
    regionId: "MAS",
    regionName: "Masaka",
    countryFlag: "🇺🇬",
    countryName: "Uganda",
  },
  GUL: {
    regionId: "GUL",
    regionName: "Gulu",
    countryFlag: "🇺🇬",
    countryName: "Uganda",
  },
  KHA: {
    regionId: "KHA",
    regionName: "Khabarovsk",
    countryFlag: "🇷🇺",
    countryName: "Russia",
  },
  NYA: {
    regionId: "NYA",
    regionName: "Nyala",
    countryFlag: "🇸🇩",
    countryName: "Sudan",
  },
  POR: {
    regionId: "POR",
    regionName: "Port Sudan",
    countryFlag: "🇸🇩",
    countryName: "Sudan",
  },
  KAS: {
    regionId: "KAS",
    regionName: "Kassala",
    countryFlag: "🇸🇩",
    countryName: "Sudan",
  },
  ALG: {
    regionId: "ALG",
    regionName: "Algiers",
    countryFlag: "🇩🇿",
    countryName: "Algeria",
  },
  ORA: {
    regionId: "ORA",
    regionName: "Oral",
    countryFlag: "🇰🇿",
    countryName: "Kazakhstan",
  },
  CON: {
    regionId: "CON",
    regionName: "Constantine",
    countryFlag: "🇩🇿",
    countryName: "Algeria",
  },
  ANN: {
    regionId: "ANN",
    regionName: "Annaba",
    countryFlag: "🇩🇿",
    countryName: "Algeria",
  },
  TUN: {
    regionId: "TUN",
    regionName: "Tunis",
    countryFlag: "🇹🇳",
    countryName: "Tunisia",
  },
  SFx: {
    regionId: "SFx",
    regionName: "Sfax",
    countryFlag: "🇹🇳",
    countryName: "Tunisia",
  },
  SOS: {
    regionId: "SOS",
    regionName: "Sousse",
    countryFlag: "🇹🇳",
    countryName: "Tunisia",
  },
  KAI: {
    regionId: "KAI",
    regionName: "Kairouan",
    countryFlag: "🇹🇳",
    countryName: "Tunisia",
  },
  CAS: {
    regionId: "CAS",
    regionName: "Casablanca",
    countryFlag: "🇲🇦",
    countryName: "Morocco",
  },
  RAB: {
    regionId: "RAB",
    regionName: "Rabat",
    countryFlag: "🇲🇦",
    countryName: "Morocco",
  },
  FES: {
    regionId: "FES",
    regionName: "Fès",
    countryFlag: "🇲🇦",
    countryName: "Morocco",
  },
  TAN: {
    regionId: "TAN",
    regionName: "Tangier",
    countryFlag: "🇲🇦",
    countryName: "Morocco",
  },
  MAP: {
    regionId: "MAP",
    regionName: "Maputo",
    countryFlag: "🇲🇿",
    countryName: "Mozambique",
  },
  BEI: {
    regionId: "BEI",
    regionName: "Beira",
    countryFlag: "🇲🇿",
    countryName: "Mozambique",
  },
  NAM: {
    regionId: "NAM",
    regionName: "Namangan",
    countryFlag: "🇺🇿",
    countryName: "Uzbekistan",
  },
  CHI: {
    regionId: "CHI",
    regionName: "Chita",
    countryFlag: "🇷🇺",
    countryName: "Russia",
  },
  LUA: {
    regionId: "LUA",
    regionName: "Luanda",
    countryFlag: "🇦🇴",
    countryName: "Angola",
  },
  HUA: {
    regionId: "HUA",
    regionName: "Huambo",
    countryFlag: "🇦🇴",
    countryName: "Angola",
  },
  LUB: {
    regionId: "LUB",
    regionName: "Lubango",
    countryFlag: "🇦🇴",
    countryName: "Angola",
  },
  KIN: {
    regionId: "KIN",
    regionName: "Kinshasa",
    countryFlag: "🇨🇩",
    countryName: "Democratic Republic of the Congo",
  },
  KISx: {
    regionId: "KISx",
    regionName: "Kisangani",
    countryFlag: "🇨🇩",
    countryName: "Democratic Republic of the Congo",
  },
  MAI: {
    regionId: "MAI",
    regionName: "Mbandaka",
    countryFlag: "🇨🇩",
    countryName: "Democratic Republic of the Congo",
  },
  KANx: {
    regionId: "KANx",
    regionName: "Kananga",
    countryFlag: "🇨🇩",
    countryName: "Democratic Republic of the Congo",
  },
  BRA: {
    regionId: "BRA",
    regionName: "Brazzaville",
    countryFlag: "🇨🇬",
    countryName: "Republic of the Congo",
  },
  POI: {
    regionId: "POI",
    regionName: "Pointe-Noire",
    countryFlag: "🇨🇬",
    countryName: "Republic of the Congo",
  },
  DOL: {
    regionId: "DOL",
    regionName: "Dolisie",
    countryFlag: "🇨🇬",
    countryName: "Republic of the Congo",
  },
  OWE: {
    regionId: "OWE",
    regionName: "Owando",
    countryFlag: "🇨🇬",
    countryName: "Republic of the Congo",
  },
  LIB: {
    regionId: "LIB",
    regionName: "Monrovia",
    countryFlag: "🇱🇷",
    countryName: "Liberia",
  },
  GB: {
    regionId: "GB",
    regionName: "Gbarnga",
    countryFlag: "🇱🇷",
    countryName: "Liberia",
  },
  KAK: {
    regionId: "KAK",
    regionName: "Kakata",
    countryFlag: "🇱🇷",
    countryName: "Liberia",
  },
  HARx: {
    regionId: "HARx",
    regionName: "Harper",
    countryFlag: "🇱🇷",
    countryName: "Liberia",
  },
  FRE: {
    regionId: "FRE",
    regionName: "Freetown",
    countryFlag: "🇸🇱",
    countryName: "Sierra Leone",
  },
  KEN: {
    regionId: "KEN",
    regionName: "Kenema",
    countryFlag: "🇸🇱",
    countryName: "Sierra Leone",
  },
  BO: {
    regionId: "BO",
    regionName: "Bo",
    countryFlag: "🇸🇱",
    countryName: "Sierra Leone",
  },
  MAK: {
    regionId: "MAK",
    regionName: "Makeni",
    countryFlag: "🇸🇱",
    countryName: "Sierra Leone",
  },
  BAN: {
    regionId: "BAN",
    regionName: "Banjul",
    countryFlag: "🇬🇲",
    countryName: "The Gambia",
  },
  KOM: {
    regionId: "KOM",
    regionName: "Kombo",
    countryFlag: "🇬🇲",
    countryName: "The Gambia",
  },
  KANz: {
    regionId: "KANz",
    regionName: "Kanifing",
    countryFlag: "🇬🇲",
    countryName: "The Gambia",
  },
  BRI: {
    regionId: "BRI",
    regionName: "Brikama",
    countryFlag: "🇬🇲",
    countryName: "The Gambia",
  },
  BAM: {
    regionId: "BAM",
    regionName: "Bamako",
    countryFlag: "🇲🇱",
    countryName: "Mali",
  },
  SIK: {
    regionId: "SIK",
    regionName: "Sikasso",
    countryFlag: "🇲🇱",
    countryName: "Mali",
  },
  KAY: {
    regionId: "KAY",
    regionName: "Kayes",
    countryFlag: "🇲🇱",
    countryName: "Mali",
  },
  KOU: {
    regionId: "KOU",
    regionName: "Koutiala",
    countryFlag: "🇲🇱",
    countryName: "Mali",
  },
  OUA: {
    regionId: "OUA",
    regionName: "Ouagadougou",
    countryFlag: "🇧🇫",
    countryName: "Burkina Faso",
  },
  BOB: {
    regionId: "BOB",
    regionName: "Bobo-Dioulasso",
    countryFlag: "🇧🇫",
    countryName: "Burkina Faso",
  },
  KOUx: {
    regionId: "KOUx",
    regionName: "Koudougou",
    countryFlag: "🇧🇫",
    countryName: "Burkina Faso",
  },
  OUAH: {
    regionId: "OUAH",
    regionName: "Ouahigouya",
    countryFlag: "🇧🇫",
    countryName: "Burkina Faso",
  },
  NIA: {
    regionId: "NIA",
    regionName: "Niamey",
    countryFlag: "🇳🇪",
    countryName: "Niger",
  },
  ZIN: {
    regionId: "ZIN",
    regionName: "Zinder",
    countryFlag: "🇳🇪",
    countryName: "Niger",
  },
  MAR: {
    regionId: "MAR",
    regionName: "Maradi",
    countryFlag: "🇳🇪",
    countryName: "Niger",
  },
  TAH: {
    regionId: "TAH",
    regionName: "Tahoua",
    countryFlag: "🇳🇪",
    countryName: "Niger",
  },
  NDJ: {
    regionId: "NDJ",
    regionName: "N'Djamena",
    countryFlag: "🇹🇩",
    countryName: "Chad",
  },
  MOU: {
    regionId: "MOU",
    regionName: "Moundou",
    countryFlag: "🇹🇩",
    countryName: "Chad",
  },
  SAR: {
    regionId: "SAR",
    regionName: "Saratov",
    countryFlag: "🇷🇺",
    countryName: "Russia",
  },
  ABE: {
    regionId: "ABE",
    regionName: "Abéché",
    countryFlag: "🇹🇩",
    countryName: "Chad",
  },
  OUAy: {
    regionId: "OUAy",
    regionName: "Ouagadougou",
    countryFlag: "🇧🇫",
    countryName: "Burkina Faso",
  },
  BOBy: {
    regionId: "BOBy",
    regionName: "Bobo-Dioulasso",
    countryFlag: "🇧🇫",
    countryName: "Burkina Faso",
  },
  NSW: {
    regionId: "NSW",
    regionName: "New South Wales",
    countryFlag: "🇦🇺",
    countryName: "Australia",
  },
  VIC: {
    regionId: "VIC",
    regionName: "Victoria",
    countryFlag: "🇦🇺",
    countryName: "Australia",
  },
  QLD: {
    regionId: "QLD",
    regionName: "Queensland",
    countryName: "Australia",
    countryFlag: "🇦🇺",
  },
  SA: {
    regionId: "SA",
    regionName: "South Australia",
    countryName: "Australia",
    countryFlag: "🇦🇺",
  },
  TAS: {
    regionId: "TAS",
    regionName: "Tasmania",
    countryName: "Australia",
    countryFlag: "🇦🇺",
  },
  ACT: {
    regionId: "ACT",
    regionName: "Australian Capital Territory",
    countryName: "Australia",
    countryFlag: "🇦🇺",
  },
  AUK: {
    regionId: "AUK",
    regionName: "Auckland",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  CAN: {
    regionId: "CAN",
    regionName: "Canterbury",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  WEL: {
    regionId: "WEL",
    regionName: "Wellington",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  OTA: {
    regionId: "OTA",
    regionName: "Otago",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  WAI: {
    regionId: "WAI",
    regionName: "Waikato",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  BOP: {
    regionId: "BOP",
    regionName: "Bay of Plenty",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  MAN: {
    regionId: "MAN",
    regionName: "Manawatū-Whanganui",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  HKB: {
    regionId: "HKB",
    regionName: "Hawke's Bay",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  TAR: {
    regionId: "TAR",
    regionName: "Taraz",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  GIS: {
    regionId: "GIS",
    regionName: "Gisborne",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  NELx: {
    regionId: "NELx",
    regionName: "Nelson",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  MARx: {
    regionId: "MARx",
    regionName: "Mary",
    countryName: "Turkmenistan",
    countryFlag: "🇹🇲",
  },
  TASx: {
    regionId: "TASx",
    regionName: "Tasman",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  WTC: {
    regionId: "WTC",
    regionName: "West Coast",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  STC: {
    regionId: "STC",
    regionName: "Southland",
    countryName: "New Zealand",
    countryFlag: "🇳🇿",
  },
  NCD: {
    regionId: "NCD",
    regionName: "National Capital District (Port Moresby)",
    countryName: "Papua New Guinea",
    countryFlag: "🇵🇬",
  },
  MOR: {
    regionId: "MOR",
    regionName: "Morobe",
    countryName: "Papua New Guinea",
    countryFlag: "🇵🇬",
  },
  EHP: {
    regionId: "EHP",
    regionName: "Eastern Highlands",
    countryName: "Papua New Guinea",
    countryFlag: "🇵🇬",
  },
  WHP: {
    regionId: "WHP",
    regionName: "Western Highlands",
    countryName: "Papua New Guinea",
    countryFlag: "🇵🇬",
  },
  ESP: {
    regionId: "ESP",
    regionName: "East Sepik",
    countryName: "Papua New Guinea",
    countryFlag: "🇵🇬",
  },
  WES: {
    regionId: "WES",
    regionName: "West Sepik",
    countryName: "Papua New Guinea",
    countryFlag: "🇵🇬",
  },
  DXB: {
    regionId: "DXB",
    regionName: "Dubai",
    countryName: "United Arab Emirates",
    countryFlag: "🇦🇪",
  },
  AUH: {
    regionId: "AUH",
    regionName: "Abu Dhabi",
    countryName: "United Arab Emirates",
    countryFlag: "🇦🇪",
  },
  SHJ: {
    regionId: "SHJ",
    regionName: "Sharjah",
    countryName: "United Arab Emirates",
    countryFlag: "🇦🇪",
  },
  DOH: {
    regionId: "DOH",
    regionName: "Doha",
    countryName: "Qatar",
    countryFlag: "🇶🇦",
  },
  RAY: {
    regionId: "RAY",
    regionName: "Al Rayyan",
    countryName: "Qatar",
    countryFlag: "🇶🇦",
  },
  WAK: {
    regionId: "WAK",
    regionName: "Al Wakrah",
    countryName: "Qatar",
    countryFlag: "🇶🇦",
  },
  KWT: {
    regionId: "KWT",
    regionName: "Kuwait City",
    countryName: "Kuwait",
    countryFlag: "🇰🇼",
  },
  AHM: {
    regionId: "AHM",
    regionName: "Ahmadi",
    countryName: "Kuwait",
    countryFlag: "🇰🇼",
  },
  JLE: {
    regionId: "JLE",
    regionName: "Jahra",
    countryName: "Kuwait",
    countryFlag: "🇰🇼",
  },
  FAR: {
    regionId: "FAR",
    regionName: "Farwaniya",
    countryName: "Kuwait",
    countryFlag: "🇰🇼",
  },
  MCT: {
    regionId: "MCT",
    regionName: "Muscat",
    countryName: "Oman",
    countryFlag: "🇴🇲",
  },
  SU: {
    regionId: "SU",
    regionName: "Sur",
    countryName: "Oman",
    countryFlag: "🇴🇲",
  },
  SLH: {
    regionId: "SLH",
    regionName: "Salalah",
    countryName: "Oman",
    countryFlag: "🇴🇲",
  },
  SOH: {
    regionId: "SOH",
    regionName: "Sohar",
    countryName: "Oman",
    countryFlag: "🇴🇲",
  },
  BAH: {
    regionId: "BAH",
    regionName: "Manama",
    countryName: "Bahrain",
    countryFlag: "🇧🇭",
  },
  MUH: {
    regionId: "MUH",
    regionName: "Muharraq",
    countryName: "Bahrain",
    countryFlag: "🇧🇭",
  },
  RIF: {
    regionId: "RIF",
    regionName: "Riffa",
    countryName: "Bahrain",
    countryFlag: "🇧🇭",
  },
  HAM: {
    regionId: "HAM",
    regionName: "Hamad Town",
    countryName: "Bahrain",
    countryFlag: "🇧🇭",
  },
  AMMx: {
    regionId: "AMMx",
    regionName: "Amman",
    countryName: "Jordan",
    countryFlag: "🇯🇴",
  },
  ZARx: {
    regionId: "ZARx",
    regionName: "Zarqa",
    countryName: "Jordan",
    countryFlag: "🇯🇴",
  },
  IRBx: {
    regionId: "IRBx",
    regionName: "Irbid",
    countryName: "Jordan",
    countryFlag: "🇯🇴",
  },
  RUS: {
    regionId: "RUS",
    regionName: "Russeifa",
    countryName: "Jordan",
    countryFlag: "🇯🇴",
  },
  AQ: {
    regionId: "AQ",
    regionName: "Aqaba",
    countryName: "Jordan",
    countryFlag: "🇯🇴",
  },
  MOW: {
    regionId: "MOW",
    regionName: "Moscow",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  SPE: {
    regionId: "SPE",
    regionName: "Saint Petersburg",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  NVS: {
    regionId: "NVS",
    regionName: "Novosibirsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  EKT: {
    regionId: "EKT",
    regionName: "Yekaterinburg",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  KZN: {
    regionId: "KZN",
    regionName: "Kazan",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  NIZ: {
    regionId: "NIZ",
    regionName: "Nizhny Novgorod",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  CHE: {
    regionId: "CHE",
    regionName: "Chelyabinsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  OMS: {
    regionId: "OMS",
    regionName: "Omsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  SAM: {
    regionId: "SAM",
    regionName: "Samara",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  ROS: {
    regionId: "ROS",
    regionName: "Rostov-on-Don",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  UFA: {
    regionId: "UFA",
    regionName: "Ufa",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  KRA: {
    regionId: "KRA",
    regionName: "Krasnoyarsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  VOR: {
    regionId: "VOR",
    regionName: "Voronezh",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  PER: {
    regionId: "PER",
    regionName: "Perm",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  VOL: {
    regionId: "VOL",
    regionName: "Volgograd",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  KRAx: {
    regionId: "KRAx",
    regionName: "Krasnodar",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  TYU: {
    regionId: "TYU",
    regionName: "Tyumen",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  TOL: {
    regionId: "TOL",
    regionName: "Tolyatti",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  IZV: {
    regionId: "IZV",
    regionName: "Izhevsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  ULY: {
    regionId: "ULY",
    regionName: "Ulyanovsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  BRY: {
    regionId: "BRY",
    regionName: "Bryansk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  KUR: {
    regionId: "KUR",
    regionName: "Kursk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  TUL: {
    regionId: "TUL",
    regionName: "Tula",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  LIP: {
    regionId: "LIP",
    regionName: "Lipetsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  ORE: {
    regionId: "ORE",
    regionName: "Orenburg",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  PEN: {
    regionId: "PEN",
    regionName: "Penza",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  SARx: {
    regionId: "SARx",
    regionName: "Saransk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  YAR: {
    regionId: "YAR",
    regionName: "Yaroslavl",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  RYA: {
    regionId: "RYA",
    regionName: "Ryazan",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  BEL: {
    regionId: "BEL",
    regionName: "Belgorod",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  VLA: {
    regionId: "VLA",
    regionName: "Vladimir",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  KURx: {
    regionId: "KURx",
    regionName: "Kurgan",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  KIR: {
    regionId: "KIR",
    regionName: "Kiribati",
    countryName: "Kiribati",
    countryFlag: "🇰🇮",
  },
  NGR: {
    regionId: "NGR",
    regionName: "Nizhny Tagil",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  MAG: {
    regionId: "MAG",
    regionName: "Magnitogorsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  TYUx: {
    regionId: "TYUx",
    regionName: "Tyumen",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  VLAy: {
    regionId: "VLAy",
    regionName: "Vladivostok",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  IRT: {
    regionId: "IRT",
    regionName: "Irkutsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  KEM: {
    regionId: "KEM",
    regionName: "Kemerovo",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  NOV: {
    regionId: "NOV",
    regionName: "Novokuznetsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  OMSx: {
    regionId: "OMSx",
    regionName: "Omsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  TOM: {
    regionId: "TOM",
    regionName: "Tomsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  BAR: {
    regionId: "BAR",
    regionName: "Barnaul",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  ULAN: {
    regionId: "ULAN",
    regionName: "Ulan-Ude",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  YAK: {
    regionId: "YAK",
    regionName: "Yakutsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  BLA: {
    regionId: "BLA",
    regionName: "Blagoveshchensk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  PET: {
    regionId: "PET",
    regionName: "Petropavlovsk-Kamchatsky",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  YUZ: {
    regionId: "YUZ",
    regionName: "Yuzhno-Sakhalinsk",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  ANA: {
    regionId: "ANA",
    regionName: "Anadyr",
    countryName: "Russia",
    countryFlag: "🇷🇺",
  },
  ALM: {
    regionId: "ALM",
    regionName: "Almaty",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  NUR: {
    regionId: "NUR",
    regionName: "Nur-Sultan",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  SHY: {
    regionId: "SHY",
    regionName: "Shymkent",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  KAR: {
    regionId: "KAR",
    regionName: "Karaganda",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  AKM: {
    regionId: "AKM",
    regionName: "Aktobe",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  PAV: {
    regionId: "PAV",
    regionName: "Pavlodar",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  UST: {
    regionId: "UST",
    regionName: "Ust-Kamenogorsk",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  SEM: {
    regionId: "SEM",
    regionName: "Semey",
    countryName: "Kazakhstan",
    countryFlag: "🇰🇿",
  },
  SAMx: {
    regionId: "SAMx",
    regionName: "Samarkand",
    countryName: "Uzbekistan",
    countryFlag: "🇺🇿",
  },
  BUK: {
    regionId: "BUK",
    regionName: "Bukhara",
    countryName: "Uzbekistan",
    countryFlag: "🇺🇿",
  },
  NUK: {
    regionId: "NUK",
    regionName: "Nukus",
    countryName: "Uzbekistan",
    countryFlag: "🇺🇿",
  },
  FARx: {
    regionId: "FARx",
    regionName: "Fergana",
    countryName: "Uzbekistan",
    countryFlag: "🇺🇿",
  },
  KOK: {
    regionId: "KOK",
    regionName: "Kokand",
    countryName: "Uzbekistan",
    countryFlag: "🇺🇿",
  },
  DUS: {
    regionId: "DUS",
    regionName: "Dushanbe",
    countryName: "Tajikistan",
    countryFlag: "🇹🇯",
  },
  KHU: {
    regionId: "KHU",
    regionName: "Khujand",
    countryName: "Tajikistan",
    countryFlag: "🇹🇯",
  },
  KUL: {
    regionId: "KUL",
    regionName: "Kulyab",
    countryName: "Tajikistan",
    countryFlag: "🇹🇯",
  },
  KHO: {
    regionId: "KHO",
    regionName: "Khorog",
    countryName: "Tajikistan",
    countryFlag: "🇹🇯",
  },
  BIS: {
    regionId: "BIS",
    regionName: "Bishkek",
    countryName: "Kyrgyzstan",
    countryFlag: "🇰🇬",
  },
  OSH: {
    regionId: "OSH",
    regionName: "Osh",
    countryName: "Kyrgyzstan",
    countryFlag: "🇰🇬",
  },
  KARx: {
    regionId: "KARx",
    regionName: "Karakol",
    countryName: "Kyrgyzstan",
    countryFlag: "🇰🇬",
  },
  TAL: {
    regionId: "TAL",
    regionName: "Nukus",
    countryName: "Uzbekistan",
    countryFlag: "🇺🇿",
  },
  ASH: {
    regionId: "ASH",
    regionName: "Ashgabat",
    countryName: "Turkmenistan",
    countryFlag: "🇹🇲",
  },
  TUR: {
    regionId: "TUR",
    regionName: "Türkmenabat",
    countryName: "Turkmenistan",
    countryFlag: "🇹🇲",
  },
  DAS: {
    regionId: "DAS",
    regionName: "Daşoguz",
    countryName: "Turkmenistan",
    countryFlag: "🇹🇲",
  },
  BAK: {
    regionId: "BAK",
    regionName: "Baku",
    countryName: "Azerbaijan",
    countryFlag: "🇦🇿",
  },
  GAN: {
    regionId: "GAN",
    regionName: "Ganja",
    countryName: "Azerbaijan",
    countryFlag: "🇦🇿",
  },
  SUM: {
    regionId: "SUM",
    regionName: "Sumqayit",
    countryName: "Azerbaijan",
    countryFlag: "🇦🇿",
  },
  MIN: {
    regionId: "MIN",
    regionName: "Mingachevir",
    countryName: "Azerbaijan",
    countryFlag: "🇦🇿",
  },
  TBI: {
    regionId: "TBI",
    regionName: "Tbilisi",
    countryName: "Georgia",
    countryFlag: "🇬🇪",
  },
  KUT: {
    regionId: "KUT",
    regionName: "Kutaisi",
    countryName: "Georgia",
    countryFlag: "🇬🇪",
  },
  BAT: {
    regionId: "BAT",
    regionName: "Batumi",
    countryName: "Georgia",
    countryFlag: "🇬🇪",
  },
  RUSx: {
    regionId: "RUSx",
    regionName: "Rustavi",
    countryName: "Georgia",
    countryFlag: "🇬🇪",
  },
  YER: {
    regionId: "YER",
    regionName: "Yerevan",
    countryName: "Armenia",
    countryFlag: "🇦🇲",
  },
  GYU: {
    regionId: "GYU",
    regionName: "Gyumri",
    countryName: "Armenia",
    countryFlag: "🇦🇲",
  },
  VAN: {
    regionId: "VAN",
    regionName: "Vanadzor",
    countryName: "Armenia",
    countryFlag: "🇦🇲",
  },
  REU: {
    regionId: "REU",
    regionName: "Réunion",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  MAY: {
    regionId: "MAY",
    regionName: "Mayotte",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  GUA: {
    regionId: "GUA",
    regionName: "Guadeloupe",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  MARy: {
    regionId: "MARy",
    regionName: "Martinique",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  GUF: {
    regionId: "GUF",
    regionName: "French Guiana",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  NCL: {
    regionId: "NCL",
    regionName: "New Caledonia",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  PYF: {
    regionId: "PYF",
    regionName: "French Polynesia",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  SPM: {
    regionId: "SPM",
    regionName: "Saint Pierre and Miquelon",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  WAL: {
    regionId: "WAL",
    regionName: "Wallis and Futuna",
    countryName: "France",
    countryFlag: "🇫🇷",
  },
  AIA: {
    regionId: "AIA",
    regionName: "Anguilla",
    countryName: "United Kingdom",
    countryFlag: "🇦🇮",
  },
  ATG: {
    regionId: "ATG",
    regionName: "Antigua and Barbuda",
    countryName: "Antigua and Barbuda",
    countryFlag: "🇦🇬",
  },
  BHS: {
    regionId: "BHS",
    regionName: "Bahamas",
    countryName: "Bahamas",
    countryFlag: "🇧🇸",
  },
  BRB: {
    regionId: "BRB",
    regionName: "Barbados",
    countryName: "Barbados",
    countryFlag: "🇧🇧",
  },
  BLZ: {
    regionId: "BLZ",
    regionName: "Belize",
    countryName: "Belize",
    countryFlag: "🇧🇿",
  },
  BMU: {
    regionId: "BMU",
    regionName: "Bermuda",
    countryName: "United Kingdom",
    countryFlag: "🇧🇲",
  },
  VGB: {
    regionId: "VGB",
    regionName: "British Virgin Islands",
    countryName: "United Kingdom",
    countryFlag: "🇻🇬",
  },
  CYM: {
    regionId: "CYM",
    regionName: "Cayman Islands",
    countryName: "United Kingdom",
    countryFlag: "🇰🇾",
  },
  CRI: {
    regionId: "CRI",
    regionName: "Costa Rica",
    countryName: "Costa Rica",
    countryFlag: "🇨🇷",
  },
  CUB: {
    regionId: "CUB",
    regionName: "Cuba",
    countryName: "Cuba",
    countryFlag: "🇨🇺",
  },
  DMA: {
    regionId: "DMA",
    regionName: "Dominica",
    countryName: "Dominica",
    countryFlag: "🇩🇲",
  },
  DOM: {
    regionId: "DOM",
    regionName: "Dominican Republic",
    countryName: "Dominican Republic",
    countryFlag: "🇩🇴",
  },
  SLV: {
    regionId: "SLV",
    regionName: "El Salvador",
    countryName: "El Salvador",
    countryFlag: "🇸🇻",
  },
  GRD: {
    regionId: "GRD",
    regionName: "Grenada",
    countryName: "Grenada",
    countryFlag: "🇬🇩",
  },
  GTM: {
    regionId: "GTM",
    regionName: "Guatemala",
    countryName: "Guatemala",
    countryFlag: "🇬🇹",
  },
  HTI: {
    regionId: "HTI",
    regionName: "Haiti",
    countryName: "Haiti",
    countryFlag: "🇭🇹",
  },
  HND: {
    regionId: "HND",
    regionName: "Honduras",
    countryName: "Honduras",
    countryFlag: "🇭🇳",
  },
  JAM: {
    regionId: "JAM",
    regionName: "Jamaica",
    countryName: "Jamaica",
    countryFlag: "🇯🇲",
  },
  NIC: {
    regionId: "NIC",
    regionName: "Nicaragua",
    countryName: "Nicaragua",
    countryFlag: "🇳🇮",
  },
  PAN: {
    regionId: "PAN",
    regionName: "Panama",
    countryName: "Panama",
    countryFlag: "🇵🇦",
  },
  KNA: {
    regionId: "KNA",
    regionName: "Saint Kitts and Nevis",
    countryName: "Saint Kitts and Nevis",
    countryFlag: "🇰🇳",
  },
  LCA: {
    regionId: "LCA",
    regionName: "Saint Lucia",
    countryName: "Saint Lucia",
    countryFlag: "🇱🇨",
  },
  VCT: {
    regionId: "VCT",
    regionName: "Saint Vincent and the Grenadines",
    countryName: "Saint Vincent and the Grenadines",
    countryFlag: "🇻🇨",
  },
  TTO: {
    regionId: "TTO",
    regionName: "Trinidad and Tobago",
    countryName: "Trinidad and Tobago",
    countryFlag: "🇹🇹",
  },
  TCA: {
    regionId: "TCA",
    regionName: "Turks and Caicos Islands",
    countryName: "United Kingdom",
    countryFlag: "🇹🇨",
  },
  VIR: {
    regionId: "VIR",
    regionName: "United States Virgin Islands",
    countryName: "United States",
    countryFlag: "🇻🇮",
  },
  ASM: {
    regionId: "ASM",
    regionName: "American Samoa",
    countryName: "United States",
    countryFlag: "🇦🇸",
  },
  COK: {
    regionId: "COK",
    regionName: "Cook Islands",
    countryName: "New Zealand",
    countryFlag: "🇨🇰",
  },
  FJI: {
    regionId: "FJI",
    regionName: "Fiji",
    countryName: "Fiji",
    countryFlag: "🇫🇯",
  },
  GUM: {
    regionId: "GUM",
    regionName: "Guam",
    countryName: "United States",
    countryFlag: "🇬🇺",
  },
  MHL: {
    regionId: "MHL",
    regionName: "Marshall Islands",
    countryName: "Marshall Islands",
    countryFlag: "🇲🇭",
  },
  FSM: {
    regionId: "FSM",
    regionName: "Micronesia",
    countryName: "Micronesia",
    countryFlag: "🇫🇲",
  },
  NRU: {
    regionId: "NRU",
    regionName: "Nauru",
    countryName: "Nauru",
    countryFlag: "🇳🇷",
  },
  NIU: {
    regionId: "NIU",
    regionName: "Niue",
    countryName: "New Zealand",
    countryFlag: "🇳🇺",
  },
  NFK: {
    regionId: "NFK",
    regionName: "Norfolk Island",
    countryName: "Australia",
    countryFlag: "🇳🇫",
  },
  MNP: {
    regionId: "MNP",
    regionName: "Northern Mariana Islands",
    countryName: "United States",
    countryFlag: "🇲🇵",
  },
  PLW: {
    regionId: "PLW",
    regionName: "Palau",
    countryName: "Palau",
    countryFlag: "🇵🇼",
  },
  PNG: {
    regionId: "PNG",
    regionName: "Papua New Guinea",
    countryName: "Papua New Guinea",
    countryFlag: "🇵🇬",
  },
  WSM: {
    regionId: "WSM",
    regionName: "Samoa",
    countryName: "Samoa",
    countryFlag: "🇼🇸",
  },
  SLP: {
    regionId: "SLP",
    regionName: "Solomon Islands",
    countryName: "Solomon Islands",
    countryFlag: "🇸🇧",
  },
  TKL: {
    regionId: "TKL",
    regionName: "Tokelau",
    countryName: "New Zealand",
    countryFlag: "🇹🇰",
  },
  TON: {
    regionId: "TON",
    regionName: "Tonga",
    countryName: "Tonga",
    countryFlag: "🇹🇴",
  },
  TUV: {
    regionId: "TUV",
    regionName: "Tuvalu",
    countryName: "Tuvalu",
    countryFlag: "🇹🇻",
  },
  VUT: {
    regionId: "VUT",
    regionName: "Vanuatu",
    countryName: "Vanuatu",
    countryFlag: "🇻🇺",
  },
  WLF: {
    regionId: "WLF",
    regionName: "Wallis and Futuna",
    countryName: "France",
    countryFlag: "🇼🇫",
  },
};
